# 🏃‍♀️ Continuous Integration and Delivery: Stable
# ==============================================
#
# 🤞

---

name: 😌 Stable CI/CD


# Driving Event
# -------------
#
# What starts this workflow: a push to a release tag

on:
    push:
        branches:
            - 'release/*'

# What to Do
# ----------
#
# Build and push to Docker Hub

jobs:
    image-build-and-push:
        name: 🌄 Image Build & Push
        runs-on: ubuntu-latest
        steps:
            # Normally build-push-action can use the Git context but the metadata-action cannot,
            # so we need to do a manual checkout action and specify the `context: .` to the
            # build-push-action. C'est la vie.
            -
                name: 💳 Checkout
                uses: actions/checkout@v3
                with:
                    lfs: true
                    token: ${{secrets.ADMIN_GITHUB_TOKEN}}
                    fetch-depth: 0
            -
                name: 🏢 Docker Buildx Setup
                uses: docker/setup-buildx-action@v2
            -
                name: 🔍 Metadata Generation
                id: meta
                uses: docker/metadata-action@v4
                with:
                    images: nasapds/github-actions-base
                    tags: |
                        type=ref,event=tag
                        type=semver,pattern={{version}}
            -
                name: 🪵 Docker Hub Login
                uses: docker/login-action@v2
                with:
                    username: ${{secrets.DOCKERHUB_USERNAME}}
                    password: ${{secrets.DOCKERHUB_TOKEN}}
            -
                name: 😤 Build & Push
                uses: docker/build-push-action@v4
                with:
                    context: .
                    push: true
                    tags: ${{steps.meta.outputs.tags}}
                    secrets: GIT_AUTH_TOKEN=${{secrets.ADMIN_GITHUB_TOKEN}}

...

# -*- mode: yaml; indent: 4; fill-column: 120; coding: utf-8 -*-
