
name: Triggered Stable CI/CD


# Driving Event
# -------------
#
# What starts this workflow: a push to a release tag

on:
    repository_dispatch:
        types: [pds-github-util-built]
    workflow_dispatch:

# What to Do
# ----------
#
# Build and push to Docker Hub when a depended-upon external repo (currently only pds-github-util)
# is built. This ensures that we have the latest and greatest dependencies in our actions base
# image.

jobs:
    image-build-and-push:
        name: 🌄 Image Build & Push
        runs-on: ubuntu-latest
        steps:
            # We need a non-shallow checkout of our repo for tag querying in future steps
            -
                name: 💳 Checkout
                uses: actions/checkout@v2
                with:
                    lfs: true
                    token: ${{secrets.ADMIN_GITHUB_TOKEN}}
                    fetch-depth: 0
            -
                name: 🏢 Docker Buildx Setup
                uses: docker/setup-buildx-action@v1
            -
                name: Query Tag
                id: query_tag
                uses: jimschubert/query-tag-action@v2
                with:
                    skip-unshallow: 'true'
            -
                name: 🔍 Metadata Generation
                id: meta
                uses: docker/metadata-action@v3
                with:
                    images: nasapds/pds-github-actions-base
                    tags: |
                        type=semver,pattern={{version}},value=${{steps.query_tag.outputs.tag}}
            -
                name: 🪵 Docker Hub Login
                uses: docker/login-action@v1
                with:
                    username: ${{secrets.DOCKER_USERNAME}}
                    password: ${{secrets.DOCKER_PASSWORD}}
            -
                name: 😤 Build & Push
                uses: docker/build-push-action@v2
                with:
                    context: .
                    push: true
                    tags: ${{steps.meta.outputs.tags}}
                    secrets: GIT_AUTH_TOKEN=${{secrets.ADMIN_GITHUB_TOKEN}}
