# 🏃‍♀️ Continuous Integration and Delivery: Unstable
# ================================================
#
# 🤞

---

name: 🤪 Unstable CI/CD


# Driving Event
# -------------
#
# What starts this workflow: a push to main

on:
    push:
        branches:
            - main


# What to Do
# ----------
#
# Build and push to Docker Hub

jobs:
    image-build-and-push:
        name: 🌄 Image Build & Push
        runs-on: ubuntu-latest
        if: github.actor != 'pdsen-ci'
        steps:
            -
                name: 🏢 Docker Buildx Setup
                uses: docker/setup-buildx-action@v1

            -
                name: 🪵 Docker Hub Login
                uses: docker/login-action@v1
                with:
                    username: ${{secrets.DOCKER_USERNAME}}
                    password: ${{secrets.DOCKER_PASSWORD}}
            -
                name: 😤 Build & Push
                uses: docker/build-push-action@v2
                with:
                    push: true
                    tags: nasapds/github-actions-base:latest
                    secrets: GIT_AUTH_TOKEN=${{secrets.ADMIN_GITHUB_TOKEN}}


...

# -*- mode: yaml; indent: 4; fill-column: 120; coding: utf-8 -*-
